CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users(
	id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
	name VARCHAR(256) NOT NULL,
	email VARCHAR(180) UNIQUE NOT NULL,
	pwd VARCHAR(180) NOT NULL
);